[2.x] #285 fixed Update All Button issue
jliddev/WowUp pull request #289
Opened 2020-10-31 19:48 UTC by Cratis1831

Update All button was still showing enabled even if there were no addons to update

Issue:
if there is an addon that is set to "ignored" but underlying has an update the "Update All" button will be enabled
so if you uncheck the ignore and update the addon
then the "Update All" button will get disabled

2020-11-01 14:39 UTC, jliddev commented on wowup-electron/src/app/components/options-app-section/options-app-section.component.ts
> +    this.setCurrentLanguage = this.wowupService.setCurrentLanguage;
this.setCurrentLanguage should be this.currentLanguage?

2020-11-01 14:39 UTC, jliddev commented on wowup-electron/src/app/components/options-app-section/options-app-section.component.ts
> +  onSetCurrentLanguageChange = (evt: MatSelectChange) => {
onCurrentLanguageChange

2020-11-01 14:40 UTC, jliddev commented on wowup-electron/src/app/components/options-app-section/options-app-section.component.html
> +  <div class="toggle">
Maybe we move this to the top?

2020-11-01 14:42 UTC, jliddev commented on wowup-electron/src/common/constants.ts
> +export const SET_LANGUAGE_PREFERENCE_KEY = "set_language";
would selected_language make more sense?

2020-11-01 14:44 UTC, jliddev commented on wowup-electron/src/app/app.component.ts
> +    this.translate.use(this._wowUpService.setCurrentLanguage);
what happens if this pref has not been set yet?

2020-11-01 14:45 UTC, jliddev requested changes
Some minor naming changes.
Maybe move the language selector to the top?
We need to initialize the preference to the current locale

2020-11-01 15:40 UTC, Cratis1831 commented on wowup-electron/src/app/pages/my-addons/my-addons.component.ts
> +          (li) => (li.needsInstall || li.needsUpdate) && !li.isIgnored
@MadenBot thx, made the change

2020-11-02 03:02 UTC, jliddev approved these changes

2020-11-02 03:02 UTC, merged