Add open folder in addon context menu
jliddev/WowUp pull request #64
Opened 2020-09-28 21:11 UTC by Xathz

Never worked with WPF before so not 100% sure I did the xaml correctly but tested and it works fine.

Note: I had to add `System.ComponentModel.Annotations` for it to build

2020-09-29 15:57 UTC, jliddev requested changes
Feature works perfectly, just some minor changes before merge. Also pull in latest Develop branch changes if you can so there's no merge conflicts.

2020-09-29 15:57 UTC, jliddev commented on WowUp.Common/WowUp.Common.csproj
> +    <PackageReference Include="System.ComponentModel.Annotations" Version="4.7.0" />
Can we remove this? I was able to build the PR without it

2020-09-29 15:57 UTC, jliddev commented on WowUp.WPF/Extensions/AddonExtensions.cs
> +        public static string GetFullFolderPath(this Addon addon, IWarcraftService warcraftService) => Path.GetFullPath(Path.Combine(warcraftService.GetAddonFolderPath(addon.ClientType), addon.FolderN
This should probably go in the IWarcraftService

2020-09-29 15:57 UTC, jliddev commented on WowUp.WPF/Utilities/FileUtilities.cs
> +        public static void OpenInFileManager(string path)
This function seems fine, but can we use the same format as StringExtensions.OpenUrlInBrowser which does basically the same thing.

2020-09-29 15:57 UTC, jliddev commented on WowUp.WPF/Views/AddonsView.xaml
> +                        <MenuItem Header="Open Folder"
This is fine, maybe move it above the Separator tag so its in the same place regardless of update status.

2020-09-29 19:14 UTC, Xathz commented
My bad didn't even see a dev branch, will close and resubmit the pr on the correct branch.

2020-09-29 19:14 UTC, closed without merging

2020-09-30 20:01 UTC, jliddev commented
Nice work :D